import { useState } from "react";
import { User } from "firebase/auth";
import { Search, ShieldAlert, ShieldCheck, Download, Loader2, AlertTriangle, ExternalLink } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { cn } from "../lib/utils";
import { GoogleGenAI } from "@google/genai";

interface ScannerProps {
  user: User | null;
  onAuthRequired: () => void;
}

interface Vulnerability {
  title: string;
  severity: "High" | "Medium" | "Low";
  description: string;
}

interface ScanResult {
  riskScore: number;
  vulnerabilities: Vulnerability[];
  recommendations: string;
  summary: string;
}

export default function Scanner({ user, onAuthRequired }: ScannerProps) {
  const [url, setUrl] = useState("");
  const [isScanning, setIsScanning] = useState(false);
  const [result, setResult] = useState<ScanResult | null>(null);
  const [error, setError] = useState("");

  const handleScan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      onAuthRequired();
      return;
    }
    if (!url) return;

    setIsScanning(true);
    setError("");
    setResult(null);

    try {
      const fullUrl = url.startsWith("http") ? url : `https://${url}`;
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });
      const prompt = `As a cybersecurity expert, perform a simulated vulnerability analysis of the website: ${fullUrl}. 
      Provide a detailed report in JSON format with the following fields:
      - riskScore (number 0-100)
      - vulnerabilities (array of objects with 'title', 'severity' (High/Medium/Low), 'description')
      - recommendations (string)
      - summary (string)
      
      Return ONLY the JSON object.`;

      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash",
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        config: { responseMimeType: "application/json" }
      });

      const analysis = JSON.parse(response.text);
      setResult(analysis);
    } catch (err) {
      console.error("Analysis error:", err);
      setError("Failed to analyze website. Please check the URL and try again.");
    } finally {
      setIsScanning(false);
    }
  };

  const downloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(10, 10, 12);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(0, 242, 255);
    doc.setFontSize(24);
    doc.text("KAFKA SECURITY REPORT", 20, 25);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(`Target URL: ${url}`, 20, 35);
    doc.text(`Date: ${new Date().toLocaleString()}`, 150, 35);

    // Risk Score
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text(`Overall Risk Score: ${result.riskScore}/100`, 20, 55);
    
    // Summary
    doc.setFontSize(12);
    doc.text("Executive Summary:", 20, 70);
    const splitSummary = doc.splitTextToSize(result.summary, 170);
    doc.text(splitSummary, 20, 80);

    // Vulnerabilities Table
    const tableData = result.vulnerabilities.map(v => [v.title, v.severity, v.description]);
    autoTable(doc, {
      startY: 100,
      head: [["Vulnerability", "Severity", "Description"]],
      body: tableData,
      headStyles: { fillColor: [0, 242, 255], textColor: [0, 0, 0] },
      margin: { top: 100 },
    });

    // Recommendations
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.text("Mitigation Recommendations:", 20, finalY);
    const splitRecs = doc.splitTextToSize(result.recommendations, 170);
    doc.text(splitRecs, 20, finalY + 10);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Kafka Cybersecurity Tool - Confidential", 20, 285);

    doc.save(`Kafka_Security_Report_${url.replace(/[^a-z0-9]/gi, "_")}.pdf`);
  };

  return (
    <div className="space-y-6">
      <div className="panel p-6">
        <div className="flex items-center justify-between mb-6">
          <h2 className="panel-title flex items-center gap-2">
            <Search className="w-4 h-4 text-accent-neon" /> Web Security Scanner
          </h2>
          <div className="flex gap-2">
            <button 
              onClick={downloadPDF}
              disabled={!result}
              className="px-3 py-1.5 bg-bg-surface border border-border-dim rounded text-[10px] font-bold uppercase hover:bg-white/5 disabled:opacity-30 transition-colors"
            >
              Export PDF
            </button>
          </div>
        </div>
        
        <form onSubmit={handleScan} className="flex gap-3">
          <div className="flex-1 bg-bg-surface border border-border-dim rounded flex items-center px-4 gap-3 focus-within:border-accent-neon transition-colors">
            <span className="text-text-dim text-xs opacity-50 font-mono">https://</span>
            <input
              type="text"
              placeholder="Enter target domain for deep analysis..."
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="flex-1 bg-transparent py-3 text-sm text-text-main outline-none placeholder:text-text-dim/50"
            />
          </div>
          <button 
            type="submit" 
            disabled={isScanning}
            className="cyber-button"
          >
            {isScanning ? <Loader2 className="w-4 h-4 animate-spin" /> : "Execute Scan"}
          </button>
        </form>
        {error && <p className="text-risk-high text-[10px] mt-3 uppercase font-bold tracking-tighter">{error}</p>}
      </div>

      <AnimatePresence>
        {isScanning && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="panel p-12 flex flex-col items-center justify-center space-y-4"
          >
            <Loader2 className="w-8 h-8 text-accent-neon animate-spin" />
            <p className="text-accent-neon font-mono text-[10px] tracking-[0.2em] animate-pulse">
              [SYSTEM] PROBING PERIMETER: {url.toUpperCase()}...
            </p>
            <div className="text-[9px] text-text-dim/50 font-mono mt-2">
              ESTABLISHING SECURE HANDSHAKE | BYPASSING WAF | ANALYZING HEADERS
            </div>
          </motion.div>
        )}

        {result && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-6"
          >
            {/* Risk Metrics */}
            <div className="panel relative overflow-hidden">
              <div className="absolute -top-2 -right-6 kafka-stamp scale-75 opacity-30">
                Verified
              </div>
              <div className="panel-header">
                <span className="panel-title">Risk Metrics</span>
              </div>
              <div className="p-6 flex flex-col items-center justify-center flex-1">
                <div className={cn(
                  "text-6xl font-mono font-black mb-1",
                  result.riskScore > 70 ? "text-risk-high" : result.riskScore > 40 ? "text-risk-med" : "text-risk-low"
                )}>
                  {result.riskScore}
                </div>
                <div className="text-[10px] text-text-dim uppercase tracking-widest">Severity Score</div>
                
                <div className="w-full mt-8 space-y-4">
                  <div className="flex justify-between items-end">
                    <span className="stat-label">Integrity</span>
                    <span className="stat-value">{100 - result.riskScore}%</span>
                  </div>
                  <div className="w-full bg-bg-surface h-1 rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-accent-neon transition-all duration-1000" 
                      style={{ width: `${100 - result.riskScore}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Executive Summary */}
            <div className="panel lg:col-span-2">
              <div className="panel-header">
                <span className="panel-title">Executive Summary</span>
                <div className="flex items-center gap-2">
                  <span className="text-[9px] text-text-dim font-mono uppercase">{url}</span>
                  <div className="badge badge-high">Live Report</div>
                </div>
              </div>
              <div className="p-6 flex-1">
                <p className="text-text-dim text-xs leading-relaxed font-mono">
                  {result.summary}
                </p>
                <div className="mt-8 pt-6 border-t border-border-dim">
                  <h4 className="stat-label mb-3">Mitigation Strategy</h4>
                  <p className="text-text-main text-xs leading-relaxed">
                    {result.recommendations}
                  </p>
                </div>
              </div>
            </div>

            {/* Vulnerabilities List */}
            <div className="panel lg:col-span-3">
              <div className="panel-header">
                <span className="panel-title">Detected Vulnerabilities</span>
              </div>
              <div className="divide-y divide-border-dim">
                {result.vulnerabilities.map((v, i) => (
                  <div key={i} className="p-4 flex items-start justify-between gap-4 hover:bg-white/5 transition-colors">
                    <div className="space-y-1">
                      <h4 className="text-xs font-bold text-text-main uppercase tracking-tight">{v.title}</h4>
                      <p className="text-[11px] text-text-dim leading-normal">{v.description}</p>
                    </div>
                    <span className={cn(
                      "badge shrink-0",
                      v.severity === "High" ? "badge-high" : v.severity === "Medium" ? "badge-med" : "badge-low"
                    )}>
                      {v.severity}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

